### ISSUE TITLE
Many Stock Tickers' June 27 Open, High, Low is 0

### ISSUE THREAD

**Issue by stockenja** [iexg/IEX-API#1078]
Run the historical chart endpoint for SPY, XLE, AAPL for the past 3 months.

You will June 27 has 0 for open, high, low and volume...

========================

New updates:

Somehow, the sandbox API have only 1 data point and it correspond to June 27:

https://sandbox.iexapis.com/stable/stock/spy/chart/3m

Maybe you guys made some mistake in your code when shuffling data around...

**Comment by Jacyle** [comment]
I also came across this issue

**Comment by evancarter-iex** [comment]
This is resolved.

**Comment by josephmaxim** [comment]
still not resolved. showing null or 0 only latestPrice is OK. 
`
{
"symbol": "AAPL",
"companyName": "Apple, Inc.",
"calculationPrice": "previousclose",
"open": 203.13,
"openTime": 1562160600231,
"close": 204.41,
"closeTime": 1562173200677,
"high": null,
"low": null,
"latestPrice": 204.41,
"latestSource": "Previous close",
"latestTime": "July 3, 2019",
"latestUpdate": 1562126400000,
"latestVolume": 11339967,
"iexRealtimePrice": null,
"iexRealtimeSize": null,
"iexLastUpdated": null,
"delayedPrice": 0,
"delayedPriceTime": 1562273990254,
"extendedPrice": 204.4,
"extendedChange": -0.01,
"extendedChangePercent": -0.00005,
"extendedPriceTime": 1562187590254,
"previousClose": 204.41,
"change": 0,
"changePercent": 0,
"iexMarketPercent": null,
"iexVolume": null,
"avgTotalVolume": 25517236,
"iexBidPrice": null,
"iexBidSize": null,
"iexAskPrice": null,
"iexAskSize": null,
"marketCap": 940506762800,
"peRatio": 17.05,
"week52High": 233.47,
"week52Low": null,
"ytdChange": 0.29439
}
`
