### ISSUE TITLE
/stock/aapl/chart/date/20190802?chartByDay=true returns data for wrong date

### ISSUE THREAD

**Issue by humenick** [iexg/IEX-API#1173]
**Clearly describe the problem**

/stock/SPY/chart/date/20190802?chartByDay=true currently returns data for 20190801. This appears to affect all symbols.

**What time did the problem occur? (with timezone)**

August 2nd, 2019

**What is the expected behavior?**

No data should be returned if the requested data cannot be returned.

**API URL (if applicable)**

/stock/SPY/chart/date/20190802?chartByDay=true

**What are the steps to reproduce the bug?**

Request /stock/SPY/chart/date/20190802?chartByDay=true with the current date.

**Comment by evancarter-iex** [comment]
@humenick What time of day did this occur?

**Comment by humenick** [comment]
@evancarter-iex 16:30 ET after market close

**Comment by humenick** [comment]
@evancarter-iex This is currently reoccurring during market hours; when requesting today’s date, data for yesterday is returned.

**Comment by f2calv** [comment]
Issue confirmed.
Running a query on 2019-08-14 at 01:15 UTC also returns the wrong data for the previous day on an international symbol. Should return close data for 2019-08-13 but instead is returning for 2019-08-12;

![wrongdaysdata](https://user-images.githubusercontent.com/16097639/62987887-508c4600-be42-11e9-9a17-dfb66da5a56a.png)

**Comment by michaeldrennen** [comment]
To add,
If you set the date to a **Saturday**, it will return **Friday's** data instead of null.
Until this is fixed, 
I need to check if the date in question is a _Business Day_ before sending the request or I will incur extra/unwanted charges to my account.

**Comment by evancarter-iex** [comment]
This is fixed. Ive added the saturday not returning null to our queue.

**Comment by f2calv** [comment]
Sorry @evancarter-iex the original problem is not fixed.
I am querying (at 05:50 UTC) for yesterdays date the 2019-09-17 and it's returning data for 2019-09-16, see below;

![image](https://user-images.githubusercontent.com/16097639/65116859-9b711e80-d9e9-11e9-9353-933dfda9a509.png)

**Comment by evancarter-iex** [comment]
@f2calv hmmm my apologies I swear this was working in my test. Reopening and Ill look into it some more today.

**Comment by evancarter-iex** [comment]
@f2calv okay this should be fixed now. Can you confirm? 

@michaeldrennen We also fixed the Saturday/sunday issue

**Comment by f2calv** [comment]
@evancarter-iex yes it's fixed, testing @02:30 UTC on 2019-09-20 for 2019-09-19 close data returns an empty price array so thank you :)

**Comment by evancarter-iex** [comment]
@f2calv @humenick No problem, closing as fixed.
