### ISSUE TITLE
Price change and change percentage are wrong for many ETFs

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#1258]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the data problem**
Price change and change percentage are wrong for many ETFs such as
icf, usmv, vnq, hedj, iwf, iws, iwd, iwn, ijr, itb, iwd

For example IWD, 

https://iextrading.com/apps/stocks/IWD

iShares Russell 1000 Value ETF (IWD)
128.53 +1.434(+1.13%)
Close as of September 25, 2019.

The actual price change is

iShares Russell 1000 Value ETF (IWD)
NYSEArca - Nasdaq Real Time Price. Currency in USD

128.53+0.61 (+0.48%)

**Data URL (The URL you used to access the data without your token):**
https://iextrading.com/apps/stocks/IWD

**What time did the problem occur (including timezone)?**
Any time

**What is the expected behavior?**

**What are the steps to reproduce**
https://iextrading.com/apps/stocks/IWD

vs.

https://finance.yahoo.com/quote/IWD?p=IWD&.tsrc=fin-srch

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by evancarter-iex** [comment]
@bishinew I am looking into this.

**Comment by evancarter-iex** [comment]
@bishinew this should be resolved now.

**Comment by evancarter-iex** [comment]
Actually found a couple more. Going to fix those.

**Comment by evancarter-iex** [comment]
Okay should be fixed now.

**Comment by bishinew** [comment]
Hi it's not fixed. Please check again this morning.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
