### ISSUE TITLE
Prob with historical stock data call

### ISSUE THREAD

**Issue by dsrapaport** [iexg/IEX-API#1271]
There seems to be an issue with the "historical prices" call.

For example, when I submit (my token is substituted as "TOKEN" below):

> https://cloud.iexapis.com/stable/stock/aapl/chart/1m?chartLast=5&token=TOKEN&filter=date,high,low,close,volume

I get the following response:

> [{"date":"2019-10-03","high":220.96,"low":215.13,"close":220.82,"volume":30352686},{"date":"2019-10-04","high":227.49,"low":223.89,"close":227.01,"volume":34755553},{"date":"2019-10-07","high":229.93,"low":225.84,"close":227.06,"volume":30889269},{**"date":"2019-10-08","high":0,"low":0,"close":227.06,"volume":0}**,{**"date":"2019-10-08"**,"high":228.06,"low":224.33,"close":224.4,"volume":29282700}]

There are two issues with the above response:

1. It repeats yesterday's date (10/8/2019), with the first instance showing high, low, and volume = 0.

2. The first instance also shows the close for 10/7/2019 (not 10/8/2019).

Is there a way that IEX can fix this back to working normally?

Thank you for your help.

*Please note: I also sent this issue to support via email (apologies - forgot that one could submit it here too).

**Comment by cchristieglg** [comment]
We are having this issue too

**Comment by GoldbergGLG** [comment]
We also noticed that the label property is missing from the last entry.  It instead a symbol property not found in the other records/objects.

**Comment by evancarter-iex** [comment]
We have been rolling out a fix for this. Should be complete shortly.

**Comment by dsrapaport** [comment]
Thank you!

**Comment by evancarter-iex** [comment]
Closing as this should be fixed

**Comment by GoldbergGLG** [comment]
Thanks for the quick response!

**Comment by GoldbergGLG** [comment]
Unfortunately we are still seeing the `change` and the `changePercent` properties is still zero.
