### ISSUE TITLE
SSL/TLS Error

### ISSUE THREAD

**Issue by kswier** [iexg/IEX-API#1491]
For the last month, every now and then, when I call the following api 

https://cloud.iexapis.com/v1/stock/market/batch

I get the error  "The request was aborted: Could not create SSL/TLS secure channel.".

I don't get this error everytime I call the api,  I just get it every once in a while.  I tried changing a few things on my end and still get the error.

Do you have any ideas on what is causing this?

**Comment by evancarter-iex** [comment]
This should be fixed.

**Comment by kswier** [comment]
I am still getting the error.  I got it on December 28th, 10:22am central.

**Comment by timpaine-iex** [comment]
@kswier what params are you passing into your batch call (please omit token)

**Comment by kswier** [comment]
https://cloud.iexapis.com/v1/stock/market/batch?symbols=XLF,XAR,SSO,GTXI&types=quot

**Comment by timpaine-iex** [comment]
@kswier is it always the same or is it random? I don't see anything out of the ordinary about that request

**Comment by kswier** [comment]
It is random.  Most of these quote api calls I make run just fine.  It is just every now and then I get this error.
