### ISSUE TITLE
[Data] 2020-12-02 chart data missing for QCOM, MOS, & more

### ISSUE THREAD

**Issue by humenick** [iexg/IEX-API#1643]
**Clearly describe the data problem**
Chart data was delayed several hours this morning for yesterday’s close. Currently, empty arrays are still being returned for some symbols when requesting 2020-12-02 chart data. Symbols affected include: QCOM, MOS, CYBR. 

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/QCOM/chart/date/20201202?chartByDay=true

**What time did the problem occur (including timezone)?**
16:00 ET, December 2nd, 2020 - present

**Comment by humenick** [comment]
QCOM & MOS have been fixed. 

CYBR, BLCN, NTRP are still missing data.

**Comment by humenick** [comment]
Missing CYBR, CRIS, LXRX for 2020-12-08.

**Comment by evancarter-iex** [comment]
Fixed

**Comment by humenick** [comment]
@evancarter-iex The following are still returning no data:
2020-12-02: NTRP
2020-12-08: CRIS, LXRX

**Comment by humenick** [comment]
@evancarter-iex This data is still missing for the above symbols and many others! I don’t understand how you can expect anyone to use the IEX API for price data while these anomalies continue to plague your API.

**Comment by McQgit** [comment]
@humenick I am not IEX and I can't speak to CRIS or LXRX.  But, NTRP last trading day was Dec1.  They merged and trade under a new symbol as of Dec2:
https://www.nasdaq.com/press-release/neurotrope-and-metuchen-pharmaceuticals-announce-completion-of-merger-forming-petros

**Comment by timpaine-iex** [comment]
I see up to date daily data for CRIS and LXRX, what are you looking at specifically? I assume minute bars, but for what days

![Screen Shot 2021-02-16 at 8 23 39 AM](https://user-images.githubusercontent.com/74613173/108068647-5a42cb00-7030-11eb-8ba2-014335bb19f3.png)
![Screen Shot 2021-02-16 at 8 23 51 AM](https://user-images.githubusercontent.com/74613173/108068650-5adb6180-7030-11eb-87b6-4c847b4a0291.png)

**Comment by humenick** [comment]
@timpaine-iex The problem is there are random days missing from the IEX daily charts endpoint. NTRP was discontinued on 2020-12-02, my bad. CRIS and LXRX traded on 2020-12-08 and the IEX API has been returning returning an empty array for that date for the past two months. SAVA on 2021-02-02 is missing. OCGN & BSQR are missing on 2021-02-08. 

https://cloud.iexapis.com/stable/stock/SAVA/chart/date/20210202?chartByDay=true
