### ISSUE TITLE
quote endpoint returning null for high and low values

### ISSUE THREAD

**Issue by dc27werner** [iexg/IEX-API#338]
## Summary
For all stocks that I have tried the quote endpoint is returning null for the high and low values.  This started on Wednesday or Thursday this week.

## Details
https://api.iextrading.com/1.0/stock/aapl/quote
is returning:
{"symbol":"AAPL","companyName":"Apple Inc.","primaryExchange":"Nasdaq Global Select","sector":"Technology","calculationPrice":"close","open":187.2,"openTime":1526650200473,"close":186.31,"closeTime":1526673600412,"high":null,"low":null,"latestPrice":186.31,"latestSource":"Close","latestTime":"May 18, 2018","latestUpdate":1526673600412,"latestVolume":18077917,"iexRealtimePrice":null,"iexRealtimeSize":null,"iexLastUpdated":null,"delayedPrice":186.35,"delayedPriceTime":1526677164231,"previousClose":186.99,"change":-0.68,"changePercent":-0.00364,"iexMarketPercent":null,"iexVolume":null,"avgTotalVolume":31986851,"iexBidPrice":null,"iexBidSize":null,"iexAskPrice":null,"iexAskSize":null,"marketCap":915739360780,"peRatio":19.15,"week52High":190.37,"week52Low":142.2,"ytdChange":0.09016012147348036}

### Date/time of issue
Started on Wednesday May 16 or Thursday May 17 and is still happening as of today Saturday May 19.

### API URL
https://api.iextrading.com/1.0/stock/aapl/quote

### What you expected to happen
The high and low values would contain a non-null value.

### What actually happened
high and low were null

**Comment by 1psmith** [comment]
You get NULL when the market is not open.  When this happens, you will see "latestSource" as "Close" or "previousClose" as in your example above.  "high" and "low" are not listed in the responses for this case although I don't think there is a good argument for not including them.

The current day's "open" is included in the result, so is seems illogical that "high" and "low" are returned as "NULL".

**Comment by joshuablackburn-iex** [comment]
This is a bug and we are working on it.  It got introduced late last week when we started splitting our delayed data by regular market hours and extended hours. I'm working to get this one resolved as soon as possible.

**Comment by joshuablackburn-iex** [comment]
Fix has been deployed and will take effect tomorrow.

**Comment by 1psmith** [comment]
Still seeing the NULLs.  Did this not go in?

"{\"symbol\":\"INTC\",\"companyName\":\"Intel Corporation\",\"primaryExchange\":\"Nasdaq Global Select\",\"sector\":\"Technology\",\"calculationPrice\":\"close\",\"open\":54.73,\"openTime\":1526995800325,\"close\":54.45,\"closeTime\":1527019200864,\"high\":**null**,\"low\":**null**,\"latestPrice\":54.45,\"latestSource\":\"Close\",\"latestTime\":\"May 22, 2018\",\"latestUpdate\":1527019200864,\"latestVolume\":19058563,\"iexRealtimePrice\":54.46,\"iexRealtimeSize\":400,\"iexLastUpdated\":1527019199850,\"delayedPrice\":54.45,\"delayedPriceTime\":1527021692000,\"extendedPrice\":54.48,\"extendedPriceTime\":1527022775897,\"previousClose\":54.32,\"change\":0.13,\"changePercent\":0.00239,\"iexMarketPercent\":0.02505,\"iexVolume\":477417,\"avgTotalVolume\":25781801,\"iexBidPrice\":0,\"iexBidSize\":0,\"iexAskPrice\":0,\"iexAskSize\":0,\"marketCap\":253737000000,\"peRatio\":14.8,\"week52High\":55.79,\"week52Low\":33.23,\"ytdChange\":0.1740473293233018}"

**Comment by bvankleeck** [comment]
Do you have an idea for when you feel this will be fixed?  I appreciate your assistance with this.

**Comment by evancarter-iex** [comment]
We will have to take a look at this on Tuesday (Monday is a holiday). Sorry for the delay.

**Comment by bvankleeck** [comment]
No worries.  Thank you for responding and have a great holiday.

**Comment by AveryData** [comment]
is this fixed? I'm still have the error.

**Comment by DanielHHowell** [comment]
I still get the error as well @joshuablackburn-iex
