### ISSUE TITLE
1 minute Chart data occasionally has value of zero for marketClose.

### ISSUE THREAD

**Issue by scottyrotten6** [iexg/IEX-API#445]
## Summary
1 minute Chart data occasionally has value of zero for marketClose for many stocks on many different days.

## Details
On 1 minute data I don't think you lose to much in just assigning the value as an average of marketHigh and marketLow, but I still felt I should bring this to your attention.

### Date/time of issue
various

### API URL

https://api.iextrading.com/1.0/stock/spy/chart/date/20180806/?filter=minute,marketOpen,marketHigh,marketLow,marketClose,marketVolume&format=csv

### What you expected to happen

I expect marketClose to always be a non-zero value.

### What actually happened

10:37 through 10:45 all have the value of 0 for marketClose.

**Comment by MaxWT** [comment]
Hey, marketClose is missing because the data that IEX aggregates and shows from other exchanges is 15 minutes delayed. So if you display the data, make sure you cut off the last 15 objects from the chart array.

**Comment by scottyrotten6** [comment]
Thanks MaxWT but the data I'm talking about is historical and its ONLY marketClose that is zero. Check out the link above for times 10:37 through 10:45.

**Comment by MaxWT** [comment]
Yes, now I see this issue.

**Comment by mfhawley** [comment]
I am currently seeing this issue on AAPL as an example right now as well which would cause some major data issue if I was to use this data...
![screenshot 2018-09-20 at 12 11 50 pm](https://user-images.githubusercontent.com/14339122/45811806-68a92300-bcce-11e8-8c86-f5fa2802a0e4.png)

**Comment by joshuablackburn-iex** [comment]
@mfhawley What day of minute bar data are you requesting in the example above?  Are you seeing this across days?

**Comment by mfhawley** [comment]
Screenshot shows the date of 20180919 for AAPL.
But you are correct. I dont believe I see it across other dates

**Comment by lvca** [comment]
Same for DGAZ, on Dec 20th 2018 after 12:38pm marketClose is 0 until the end of the day!

https://api.iextrading.com/1.0/stock/UGAZ/chart/date/20181220

**Comment by mfhawley** [comment]
@joshuablackburn-iex @iex-jenkins 

IEX,

Did you get a chance to look into this. Still many instances this is happening. GOOG is an example of this issue happening in todays data (12/31/18) between 12:50 and 13:00. The marketClose is zero.

**Comment by mfhawley** [comment]
Another example is data on 1/3/19 between 14:04 and 14:10 and several other areas from that day have marketHigh's that are clearly erroneous as they jump 3% or more during those minute then return back to normal
![image](https://user-images.githubusercontent.com/14339122/50692524-14118580-0fe9-11e9-8c72-feb2fe2c19c0.png)

**Comment by lvca** [comment]
@mfhawley have you had the chance to compare IEX data with barchart?

https://marketdata.websol.barchart.com/getHistory.json?apikey=<yourkey>&symbol=UGAZ&type=minutes&startDate=20181227

**Comment by mfhawley** [comment]
Are you referring to API data provided by barchart com or the barcharts on their website?
Barchart API is likely much more expensive.
But they're MMM chart definitely looks more accurate than this clearly incorrect data returned by IEX

![screenshot_2019-01-04-06-57-55](https://user-images.githubusercontent.com/14339122/50694820-c1879780-0fef-11e9-92c8-523b13f9b0b6.png)

**Comment by lvca** [comment]
The API is Free for `getQuote` and `getHistory` only. More than enough for this use case. You can ask for a free key. But I never compared the 2 datasets. The problem also is that there is not an official truth where I can check it.

**Comment by mfhawley** [comment]
I need this data for commercial purposes in large call/data volumes so any free barchart service would not satisfy that. Thanks though

**Comment by martyh1** [comment]
I noticed the 0's for apple for marketClose also today (1/15/19).  Is this getting looked at still?

Another question.  If the value returned is "null" for close or marketClose, does that mean there were no trades on IEX or entire market? I thought "-1" represented no trades?

**Comment by xmanko** [comment]
Here a plot for AAPL showing the missing close values, 1 min tick, for the last 30 days.
**In "orange" the close value is zero.** There is also a spike at :
```
                     Open   High    Low  Close Volume
2019-01-29 09:59:00 157.4 222.68 157.23 222.68  56336
```
![aapl_iex jpg](https://user-images.githubusercontent.com/47507267/52540349-94e53f00-2d56-11e9-9a3d-583804cf4cb0.jpeg)

**Comment by mfhawley** [comment]
This issue is pretty bad. And it's not just Apple. It's across many many stocks. And they have the same issues in the new IEX Cloud paid data service so pretty upsetting this is the kind of data they provide when you pay for it. And have yet to see really customer support or fix of any kind for this

**Comment by joshuablackburn-iex** [comment]
We've identified this issue as the result of late trade reporting on the SIP. The fix has been implemented and should be through QA shortly. The goal is to get this rolled out in the next day or two.

**Comment by mfhawley** [comment]
Great to hear. Will look out for it. Thanks for the update, Josh!

**Comment by xmanko** [comment]
It's working now! No more zero values for intraday close price!
Congrats !! 

![aapl-iex-v2](https://user-images.githubusercontent.com/47507267/52651326-f7a31b80-2eb9-11e9-838a-200ae92e2b49.jpeg)

**Comment by evancarter-iex** [comment]
Sorry it took so long on our end, but glad its fixed now.

**Comment by xmanko** [comment]
@evancarter-iex I am so sorry :-( I had switched back my data feed to another provider and forget about it .... 
sadly the issue is not yet resolved on IEX. I still get zero close value with IEX. 
Sorry for the confusion ...

**Comment by mfhawley** [comment]
Yes, I am still seeing issues. Not always the marketclose of zero issues but issues where the price randomly just very high or very low which is another obvious error
![screenshot_2019-02-12-17-05-02](https://user-images.githubusercontent.com/14339122/52679053-a0686f80-2ee8-11e9-8d0e-f7f8387c50a0.png)
![screenshot_2019-02-12-17-04-51](https://user-images.githubusercontent.com/14339122/52679054-a0686f80-2ee8-11e9-9eea-f7d044aac652.png)

**Comment by evancarter-iex** [comment]
This should be fixed for IEX Cloud

**Comment by djimoh5** [comment]
1 min chart data is returning null for pricing fields (open, high, low, close, average) for several different bars.

Symbol: AAPL
Date: Current day, which as of this writing is 4/16/2020
https://cloud.iexapis.com/v1/stock/AAPL/chart/1d

Ex.
{"date":"2020-04-16","minute":"10:42","label":"10:42 AM","high":null,"low":null,"open":null,"close":null,"average":null,"volume":0,"notional":0,"numberOfTrades":0

{"date":"2020-04-16","minute":"10:56","label":"10:56 AM","high":null,"low":null,"open":null,"close":null,"average":null,"volume":0,"notional":0,"numberOfTrades":0}

**Comment by Pfuster12** [comment]
I have the same issue as @djimoh5 , I am getting null values for intraday data even 1 day after:
https://sandbox.iexapis.com/stable/stock/AAPL/intraday-prices?chartInterval=5&token={token}

```
{
date: "2020-06-09",
minute: "15:25",
label: "3:25 PM",
high: null,
low: null,
open: null,
close: null,
average: null,
volume: 0,
notional: 0,
numberOfTrades: 0
}
```

This is almost 24 hours after.
