### ISSUE TITLE
IEX Cloud Quote endpoint no update

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#643]
## Summary

IEX Cloud Quote endpoint no update today 9:35 am

cloud.iexapis.com/beta/stock/market/quote ...

volume correct prices from yesterday 

[{"symbol":"AAPL","open":167.48,"high":171.655,"low":167.28,"latestUpdate":1549238400000,"latestPrice":171.25,"latestVolume":2787167},{"symbol":"AMD","open":24.45,"high":24.66,"low":24.07,"latestUpdate":1549238400000,"latestPrice":24.13,"latestVolume":13891554},{"symbol":"AMRN","open":16.91,"high":17.047,"low":16.2,"latestUpdate":1549238400000,"latestPrice":16.41,"latestVolume":134080},{"symbol":"AIG","open":43.68,"high":44.245,"low":43.62,"latestUpdate":1549410766285,"latestPrice":43.99,"latestVolume":92480},{"symbol":"CRZO","open":12.66,"high":13.05,"low":12.56,"latestUpdate":1549410053159,"latestPrice":13.03,"latestVolume":70443},{"symbol":"ACHC","open":27.7,"high":27.94,"low":27.01,"latestUpdate":1549401084594,"latestPrice":27.79,"latestVolume":25466},{"symbol":"ARNA","open":46.37,"high":47.79,"low":45.92,"latestUpdate":1549402565798,"latestPrice":47.77,"latestVolume":13357},{"symbol":"HLF","open":60.5,"high":61.49,"low":60.3,"latestUpdate":1549401350289,"latestPrice":60.89,"latestVolume":17800}]

api.iextrading.com/1.0/stock/market/quote ...

works

[{"symbol":"AAPL","open":167.48,"high":171.655,"low":167.28,"latestUpdate":1549377385119,"latestPrice":174.19,"latestVolume":2769022},{"symbol":"AMD","open":24.45,"high":24.66,"low":24.07,"latestUpdate":1549377386162,"latestPrice":23.54,"latestVolume":13865062},{"symbol":"AMRN","open":16.91,"high":17.047,"low":16.2,"latestUpdate":1549377254240,"latestPrice":16.59,"latestVolume":134174},{"symbol":"AIG","open":43.68,"high":44.245,"low":43.62,"latestUpdate":1549377321971,"latestPrice":43.55,"latestVolume":90415},{"symbol":"CRZO","open":12.66,"high":13.05,"low":12.56,"latestUpdate":1549377375450,"latestPrice":12.93,"latestVolume":68370},{"symbol":"ACHC","open":27.7,"high":27.94,"low":27.01,"latestUpdate":1549377362734,"latestPrice":27.85,"latestVolume":25473},{"symbol":"ARNA","open":46.37,"high":47.79,"low":45.92,"latestUpdate":1549377260419,"latestPrice":48.06,"latestVolume":12361},{"symbol":"HLF","open":60.5,"high":61.49,"low":60.3,"latestUpdate":1549377015375,"latestPrice":61.52,"latestVolume":17730}]

**Comment by StockConsultant** [comment]
maybe you guys are working on the open high low data

**Comment by joshuablackburn-iex** [comment]
We are looking at it now. The price seems to be up to date, but I'm checking our cleanup job to make sure it wipes out previous day data.

**Comment by StockConsultant** [comment]
thanks!

**Comment by joshuablackburn-iex** [comment]
Rolled out a fix to our nightly jobs. This should be resolved for the open tomorrow.

**Comment by StockConsultant** [comment]
@joshuablackburn-iex 

9:36am I'm still getting yesterdays data for the Quote endpoint volume is correct 

https://cloud.iexapis.com/beta/stock/market/quote

[{"symbol":"AAPL","open":174.8,"high":175.57,"low":172,"latestUpdate":1549411200000,"latestPrice":174.24,"latestVolume":1717720},{"symbol":"AMD","open":23.63,"high":24.14,"low":22.96,"latestUpdate":1549411200000,"latestPrice":23.26,"latestVolume":4739876},{"symbol":"AMRN","open":16.16,"high":16.3,"low":15.82,"latestUpdate":1549411200000,"latestPrice":16.23,"latestVolume":184900},{"symbol":"AMRN","open":16.16,"high":16.3,"low":15.82,"latestUpdate":1549411200000,"latestPrice":16.23,"latestVolume":184900},{"symbol":"AIG","open":43.65,"high":43.84,"low":43.41,"latestUpdate":1549582030164,"latestPrice":43.41,"latestVolume":52809},{"symbol":"CRZO","open":12.63,"high":12.79,"low":12.44,"latestUpdate":1549411200000,"latestPrice":12.52,"latestVolume":38914},{"symbol":"ACHC","open":27.65,"high":28.107,"low":27.255,"latestUpdate":1549573793705,"latestPrice":27.72,"latestVolume":8414},{"symbol":"ARNA","open":48.88,"high":49.35,"low":47.49,"latestUpdate":1549575679308,"latestPrice":48.45,"latestVolume":2880},{"symbol":"HLF","open":60.94,"high":60.95,"low":59.8,"latestUpdate":1549573357957,"latestPrice":60.71,"latestVolume":36883}]

**Comment by StockConsultant** [comment]
at 9:46pm I'm starting to see updates on the Quote end point for Low and latest prices, Open and High are still yesterdays prices, old API 1.0 has all correct open, high, low and latest (it also does take the old API 1.0  15 mins to fill in the correct open, high and low prices but the latest price and volume is ready at open of market)

{"symbol":"AAPL","open":174.8,"high":175.57,"low":171.8,"latestUpdate":1549550769359,"latestPrice":172.16,"latestVolume":2959065},{"symbol":"AMD","open":23.63,"high":24.14,"low":22.81,"latestUpdate":1549550766931,"latestPrice":22.7,"latestVolume":10807227},{"symbol":"AMRN","open":16.16,"high":16.3,"low":15.82,"latestUpdate":1549550742751,"latestPrice":15.94,"latestVolume":471250},{"symbol":"AMRN","open":16.16,"high":16.3,"low":15.82,"latestUpdate":1549550742751,"latestPrice":15.94,"latestVolume":471250},{"symbol":"AIG","open":43.65,"high":43.84,"low":43.1,"latestUpdate":1549550744671,"latestPrice":43.19,"latestVolume":161371},{"symbol":"CRZO","open":12.63,"high":12.79,"low":12.35,"latestUpdate":1549550752263,"latestPrice":12.11,"latestVolume":306353},{"symbol":"ACHC","open":27.65,"high":28.107,"low":27.255,"latestUpdate":1549549925389,"latestPrice":27.51,"latestVolume":16752},{"symbol":"ARNA","open":48.88,"high":49.35,"low":47.29,"latestUpdate":1549550584196,"latestPrice":47.42,"latestVolume":9573},{"symbol":"HLF","open":60.94,"high":60.95,"low":59.63,"latestUpdate":1549550636609,"latestPrice":60.3,"latestVolume":60443}]

**Comment by StockConsultant** [comment]
9:52am open prices are now correct, high prices are still based on yesterday

[{"symbol":"AAPL","open":172.32,"high":175.57,"low":171.8,"latestUpdate":1549551071785,"latestPrice":172.28,"latestVolume":3441016},{"symbol":"AMD","open":23,"high":24.14,"low":22.81,"latestUpdate":1549551071964,"latestPrice":22.66,"latestVolume":12981185},{"symbol":"AMRN","open":16.11,"high":16.3,"low":15.65,"latestUpdate":1549551042022,"latestPrice":15.93,"latestVolume":553127},{"symbol":"AMRN","open":16.11,"high":16.3,"low":15.65,"latestUpdate":1549551042022,"latestPrice":15.93,"latestVolume":553127},{"symbol":"AIG","open":43.18,"high":43.84,"low":43.1,"latestUpdate":1549551052256,"latestPrice":43.17,"latestVolume":201236},{"symbol":"CRZO","open":12.41,"high":12.79,"low":12.04,"latestUpdate":1549551028200,"latestPrice":12.08,"latestVolume":379085},{"symbol":"ACHC","open":27.5,"high":28.107,"low":27.255,"latestUpdate":1549551018141,"latestPrice":27.34,"latestVolume":21424},{"symbol":"ARNA","open":47.6,"high":49.35,"low":47.282,"latestUpdate":1549550584196,"latestPrice":47.42,"latestVolume":11636},{"symbol":"HLF","open":59.84,"high":60.95,"low":59.63,"latestUpdate":1549551057059,"latestPrice":60.14,"latestVolume":89780}]
