### ISSUE TITLE
Stale quotes from day before

### ISSUE THREAD

**Issue by McQgit** [iexg/IEX-API#683]
## Summary
At 9:50pm on Feb14 eastern, prices are from Feb 13 close for many tickers.

## Details
Just review the API results shown below - clearly there is wrong quote data

### Date/time of issue
9:50pm Feb14 eastern

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=sbux&types=quote,previous,ohlc

### What you expected to happen
Expected quotes from Feb14 close

### What actually happened
{
  "SBUX": {
    "quote": {
      "symbol": "SBUX",
      "companyName": "Starbucks Corporation",
      "primaryExchange": "Nasdaq Global Select",
      "sector": "Consumer Cyclical",
      "calculationPrice": "previousclose",
      "open": 70.13,
      "openTime": 1550154600669,
      "close": 70.51,
      "closeTime": 1550091600269,
      "high": 71.54,
      "low": 69.97,
      "latestPrice": 70.51,
      "latestSource": "Previous close",
      "latestTime": "February 13, 2019",
      "latestUpdate": 1550016000000,
      "latestVolume": 9429109,
      "iexRealtimePrice": 70.82,
      "iexRealtimeSize": 100,
      "iexLastUpdated": 1550177991280,
      "delayedPrice": 70.81,
      "delayedPriceTime": 1550178000238,
      "extendedPrice": 70.82,
      "extendedChange": 0.31,
      "extendedChangePercent": 0.0044,
      "extendedPriceTime": 1550181538774,
      "previousClose": 70.51,
      "change": 0,
      "changePercent": 0,
      "iexMarketPercent": 0.05981,
      "iexVolume": 563955,
      "avgTotalVolume": 12362457,
      "iexBidPrice": 0,
      "iexBidSize": 0,
      "iexAskPrice": 0,
      "iexAskSize": 0,
      "marketCap": 87686236000,
      "peRatio": 29.14,
      "week52High": 71.54,
      "week52Low": 47.37,
      "ytdChange": 0.10195808152083038
    },
    "previous": {
      "symbol": "SBUX",
      "date": "2019-02-13",
      "open": 69.81,
      "high": 70.6,
      "low": 69.8,
      "close": 70.51,
      "volume": 10264422,
      "unadjustedVolume": 10264422,
      "change": 0.76,
      "changePercent": 1.09,
      "vwap": 70.1973
    },
    "ohlc": {
      "open": {
        "price": 70.13,
        "time": 1550154600669
      },
      "close": {
        "price": 70.51,
        "time": 1550091600269
      },
      "high": 71.54,
      "low": 69.97
    }
  }
}

### Other Information (sample code, links, etc.)
A couple other tickers with same problem - PEP, PG, TROW but I saw many others (more than 20 of the 50 I looked at)

**Comment by joshuablackburn-iex** [comment]
This should be resolved now. We are investigating some late reporting of close prices that occurred when mutual fund and otc were introduced. We have a new end of day process in QA that should speed up processing of overnight files.

**Comment by McQgit** [comment]
No, not resolved.  Use url I provided in post and you'll see the "latest" is showing a close for Feb 13.  The previousClose data is now right, fwiw.

**Comment by stockgainsmobile** [comment]
Seeing the same issue with srne and others
