### ISSUE TITLE
Today-Earnings returning no data

### ISSUE THREAD

**Issue by imMatt** [iexg/IEX-API#770]
## Summary

I'm trying to use the /today-earnings endpoint and not recieving results, despite other websites showing that earnings are being published today.

### Date/time of issue

1:43PM ACST 12 March 2019

### API URL

https://cloud.iexapis.com/beta/stock/market/today-earnings
### What you expected to happen

Recieve a list of todays earnings

### What actually happened

Empty data is returned

{"bto":[],"amc":[]}

**Comment by joshuablackburn-iex** [comment]
Fixed.

**Comment by mchennupati** [comment]
Hi, it appears this bug is back again, i again see empty, when I try to pull earnings today. {"bto":[],"amc":[],"other":[]}
Am I missing something ? thanks.
