### ISSUE TITLE
Dividends info returning no data today

### ISSUE THREAD

**Issue by estrnod** [iexg/IEX-API#776]
## Summary
Getting a return code 200 but everything I try returns an empty array.

## Details
This worked when I tried it out when I signed up, but I am in testing and getting "[]" for all attempts for various stocks, where the range is "5y" or "next".  I am hitting "beta" - is there a live version, or a list of versions?
Is this something that only works during trading time, not after-hours?

### Date/time of issue
3/13/2019, around 7pm MST.

### API URL

https://cloud.iexapis.com/beta/stock/XOM/dividends/next?filter=exDate%2CpaymentDate%2CrecordDate%2Camount&token={my token}
or 
https://cloud.iexapis.com/beta/stock/XOM/dividends/next?token={my token}
(I took out the filter just to see if it was causing a problem, but still returning empty array).

### What you expected to happen
An array with one or more dividends (all the stocks I am trying are dividend stocks).

### What actually happened
Consistently returning an empty array.

**Comment by estrnod** [comment]
I may be confusing what worked before - I have this URL which still works:
https://cloud.iexapis.com/beta/tops?token={my token}&symbols=aapl

I don't know if the dividends URL has worked for me in the past, but I think I have it correct as per the API docs.

**Comment by tsnethen** [comment]
I'm having a similar problem, but only on certain stock symbols. My current database has 95 stocks that I am tracking. I can get the price for all of 95 the stock/price Get call. But for 13 of the 95, I only get [ ] returned when asking for1 year. All of these stocks have paid a dividend with the last 12 months.
Here is an example of a very common stock, GLW, which is Corning Inc. Their ExDate is 2019-02-27 with a PaymentDate of 2019-03-29 and an Amount of 0.20

The call for the price works fine.
https://cloud.iexapis.com/beta/stock/glw/price?token=MyToken

The call for the dividend info for 1 year returns nothing.
https://cloud.iexapis.com/beta/stock/glw/dividends/1y?token=MyToken

For this particular stock, if you run it for 5 years, you actually get a result, but it shows the most current ExDate of 2017-11-15.
https://cloud.iexapis.com/beta/stock/glw/dividends/5y?token=MyToken

[{"exDate":"2017-11-15","paymentDate":"2017-12-15","recordDate":"2017-11-16","declaredDate":"2017-10-04","amount":0.155,"flag":"No Change QoQ"},{"exDate":"2017-08-29","paymentDate":"2017-09-29","recordDate":"2017-08-31","declaredDate":"2017-07-19","amount":0.155,"flag":"No Change QoQ"},{"exDate":"2017-05-26","paymentDate":"2017-06-30","recordDate":"2017-05-31","declaredDate":"2017-04-27","amount":0.155,"flag":"No Change QoQ"},{"exDate":"2017-02-24","paymentDate":"2017-03-31","recordDate":"2017-02-28","declaredDate":"2017-02-01","amount":0.155,"flag":"Increase"},{"exDate":"2016-11-15","paymentDate":"2016-12-15","recordDate":"2016-11-17","declaredDate":"2016-10-05","amount":0.135,"flag":"No Change QoQ"},{"exDate":"2016-08-29","paymentDate":"2016-09-30","recordDate":"2016-08-31","declaredDate":"2016-07-20","amount":0.135,"flag":"No Change QoQ"},{"exDate":"2016-05-26","paymentDate":"2016-06-30","recordDate":"2016-05-31","declaredDate":"2016-04-28","amount":0.135,"flag":"No Change QoQ"},{"exDate":"2016-02-23","paymentDate":"2016-03-31","recordDate":"2016-02-25","declaredDate":"2016-02-03","amount":0.135,"flag":"Increase"},{"exDate":"2015-11-11","paymentDate":"2015-12-11","recordDate":"2015-11-13","declaredDate":"2015-10-07","amount":0.12,"flag":"No Change QoQ"},{"exDate":"2015-08-27","paymentDate":"2015-09-30","recordDate":"2015-08-31","declaredDate":"2015-07-15","amount":0.12,"flag":"No Change QoQ"},{"exDate":"2015-05-27","paymentDate":"2015-06-30","recordDate":"2015-05-29","declaredDate":"2015-04-29","amount":0.12,"flag":"No Change QoQ"},{"exDate":"2015-02-25","paymentDate":"2015-03-31","recordDate":"2015-02-27","declaredDate":"2014-12-03","amount":0.12,"flag":"Increase"},{"exDate":"2014-11-12","paymentDate":"2014-12-12","recordDate":"2014-11-14","declaredDate":"2014-10-01","amount":0.1,"flag":"No Change QoQ"},{"exDate":"2014-08-27","paymentDate":"2014-09-30","recordDate":"2014-08-29","declaredDate":"2014-07-16","amount":0.1,"flag":"No Change QoQ"},{"exDate":"2014-05-28","paymentDate":"2014-06-30","recordDate":"2014-05-30","declaredDate":"2014-04-29","amount":0.1,"flag":"No Change QoQ"}]

**Comment by evancarter-iex** [comment]
We are looking into this

**Comment by tsnethen** [comment]
Here are some of symbols where I'm seeing this problem:
AMZA, BDJ, BSCJ, BSCK, BSCL, BSCM, BSCN, BXMX, ECC, EFT, EOS, GLW, JQC, NVG, PFFA, PFFR, QQQX, TYG, & UTG
If I lookup these securities at dividendchannel.com, all of their current information is there.

**Comment by evancarter-iex** [comment]
@tsnethen GLW should be fixed

We are still looking into the others

**Comment by evancarter-iex** [comment]
@estrnod https://cloud.iexapis.com/beta/stock/xom/dividends/1y?token= returns data for XOM, the default call only does last 1 month and its been longer than a month since their last dividend, which is why its returning nothing. They dont have any upcoming dates listed either, as far as I can tell (hence the empty return in /next)

**Comment by estrnod** [comment]
https://cloud.iexapis.com/beta/stock/BTU/dividends/next?token=...
https://cloud.iexapis.com/beta/stock/KHC/dividends/next?token=...
https://cloud.iexapis.com/beta/stock/GPC/dividends/next?token=...
https://cloud.iexapis.com/beta/stock/MRK/dividends/next?token=...
The aforementioned all have upcoming declared dividends (according to the 5y API call), but are still returning "[]".  PM and TSN are returning upcoming dividend data with "next".

**Comment by evancarter-iex** [comment]
@estrnod dividends/next is based on exDate. Hope that helps

**Comment by estrnod** [comment]
I guess technically it does, but as I'm trying to see upcoming payments into an account, it's not really useful.

**Comment by evancarter-iex** [comment]
@estrnod could you file a ticket asking for something along those lines, so we can add it the queue of things we need to look at. Thanks

**Comment by estrnod** [comment]
Done; see https://github.com/iexg/IEX-API/issues/792

**Comment by tsnethen** [comment]
Confirmed that GLW is properly returning the dividend information.
Since this item has been closed, do you need me to open a separate ticket for the other Symbols that are still not working?
AMZA, BDJ, BSCJ, BSCK, BSCL, BSCM, BSCN, BXMX, ECC, EFT, EOS, JQC, NVG, PFFA, PFFR, QQQX, TYG, & UTG

**Comment by evancarter-iex** [comment]
@tsnethen we are aware of those. it really falls under #668 and/or #654 which we are aware of and working on ASAP
