### ISSUE TITLE
The documentation does not include information about the exchange name for the symbol.

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#778]
## Summary
here: [https://iexcloud.io/docs/api/#symbols](https://iexcloud.io/docs/api/#symbols)
response Attributes forget add exchange name

![Снимок экрана 2019-03-14 в 14 06 17](https://user-images.githubusercontent.com/40538167/54352280-58ad4300-4662-11e9-96b7-b1c0a76c8e1e.png)

**Comment by evancarter-iex** [comment]
Fixed now

**Comment by hamermike** [comment]
This is still an issue in the documentation as of 3/22/2019.

**Comment by evancarter-iex** [comment]
@hamermike ah I added to the international symbols, not the symbols symbols. Added now, will be pushed out when deploy our docs again (sometime today)
