### ISSUE TITLE
Incorrect "announceTime" on /earnings endpoint on IEXcloud

### ISSUE THREAD

**Issue by ajflores1604** [iexg/IEX-API#840]
## Summary
When looking for the time earnings were posted historically (annouceTime), the new IEXcloud endpoint returns "DMT" for some results, which the documentation lists as "during trading hours". However when comparing to the actual posted times on the relevant newswires, many times this should be correctly stated as before market hours or after market hours. I'm not sure if this is an issue with IEX or their new data providers.

## Details
I'm not sure how pervasive it is, but one specific recent example I can point to is looking up historical times for ticker 'LL'. The old 1.0 iex endpoint correctly had it listed as 'BTO' for before market open (actual posting time for the last 4 quarters has been either 6 am or 6:30 am EST), however the new iex cloud service returns 'DMT' for all instances. I have found similar discrepancies for other tickers. 
### Date/time of issue
4/7/19 between the hours of 4pm and 9pm

### API URL
https://cloud.iexapis.com/beta/stock/ll/earnings/4/

### What you expected to happen
"announceTime": 'BTO'

### What actually happened
"announceTime": 'DMT'

**Comment by joshuablackburn-iex** [comment]
Fixed

**Comment by ajflores1604** [comment]
How long should I expect it to take for the 'fix' to take effect? Pulling up the single example I mentioned in my initial issue> https://cloud.iexapis.com/beta/stock/ll/earnings/4/ > I'm still getting the incorrect 'DMT' label for announceTime. Here is a direct copy of what was returned to me on a fresh reload, after clearing cache. 

{"symbol":"LL","earnings":[{"actualEPS":-1.99,"consensusEPS":0.38,"announceTime":"DMT","numberOfEstimates":13,"EPSSurpriseDollar":-2.37,"EPSReportDate":"2019-03-18","fiscalPeriod":"Q4 2018","fiscalEndDate":"2018-12-31","yearAgo":0.1,"yearAgoChangePercent":-20.9},{"actualEPS":0.21,"consensusEPS":0.18,"announceTime":"DMT","numberOfEstimates":12,"EPSSurpriseDollar":0.03,"EPSReportDate":"2018-10-30","fiscalPeriod":"Q3 2018","fiscalEndDate":"2018-09-30","yearAgo":-0.66,"yearAgoChangePercent":-1.3182},{"actualEPS":-0.05,"consensusEPS":0.25,"announceTime":"DMT","numberOfEstimates":12,"EPSSurpriseDollar":-0.3,"EPSReportDate":"2018-07-31","fiscalPeriod":"Q2 2018","fiscalEndDate":"2018-06-30","yearAgo":0.16,"yearAgoChangePercent":-1.3125},{"actualEPS":-0.07,"consensusEPS":-0.03,"announceTime":"DMT","numberOfEstimates":12,"EPSSurpriseDollar":-0.04,"EPSReportDate":"2018-05-01","fiscalPeriod":"Q1 2018","fiscalEndDate":"2018-03-31","yearAgo":-0.93,"yearAgoChangePercent":-0.9247}]}
