### ISSUE TITLE
CMSS and other symbols are returning incorrect company and prices

### ISSUE THREAD

**Issue by mikezliu** [iexg/IEX-API#937]
**Clearly describe the data problem**

Call the batch quotes endpoint to get prices for CMSS: https://cloud.iexapis.com/stable/stock/market/batch?symbols=CMSS&types=quote&token=token

Notice the company returned is 'Kaixin Auto Holdings'. The price is 3.7. Now look on bloomsberg, yahoo finance or any other financial website, and CMSS is listed as 'CM Seven Star Acquisition Corporation' with price of 2.81. If you call SSE, the IEX cloud returns the correct company.

{
    "CMSS": {
        "quote": {
            "symbol": "CMSS",
            "companyName": "Kaixin Auto Holdings",
            "calculationPrice": "close",
            "open": 3.65,
            "openTime": 1556717400806,
            "close": 3.7,
            "closeTime": 1556740800474,
            "high": 3.69,
            "low": 3.25,
            "latestPrice": 3.7,
            "latestSource": "Close",

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/stable/stock/market/batch?symbols=CMSS&types=quote&token=token

**What time did the problem occur (including timezone)?**

May 7, 1am EDT

**What is the expected behavior?**

CMSS should return the correct company and price. The prices and company being returned is for another company.

**What are the steps to reproduce**

Call https://cloud.iexapis.com/stable/stock/market/batch?symbols=CMSS&types=quote&token=token

**Your environment (e.g. browser, OS, API version, language):**

Web API

**Additional context**

**Comment by evancarter-iex** [comment]
This should be fixed now. Full changes should be deployed overnight. Let us know if you see any additional issues thanks.

**Comment by mikezliu** [comment]
I just checked now, and it's still returning Kaixin Auto Holdings. When is the fix expected to go into effect?

https://cloud.iexapis.com/stable/stock/market/batch?symbols=CMSS&types=quote&token=..

{
    "CMSS": {
        "quote": {
            "symbol": "CMSS",
            "companyName": "Kaixin Auto Holdings",
            "calculationPrice": "sip",
            "open": 3.65,
            "openTime": 1556717400806,
            "close": 2.81,
            "closeTime": 1556740800474,
            "high": 3.58,
            "low": 3.011,

**Comment by mikezliu** [comment]
Hi - it's currently ~5:30 am EDT and I still see this issue. Could you let me know when the fix has been deployed so I can check again? Thanks

**Comment by evancarter-iex** [comment]
@mikezliu Hey there, This news release covers whats going on https://www.globenewswire.com/news-release/2019/05/01/1813486/0/en/CM-Seven-Star-Announces-Consummation-of-Business-Combination-with-Renren-Inc-s-Kaixin-Auto-Group.html

"CM Seven Star’s company name has been changed to Kaixin Auto Holdings and its ticker symbol on the Nasdaq stock exchange will change from “CMSS” to “KXIN” effective at the start of trading on May 2, 2019.  No action is needed from current CM Seven Star shareholders in relation to the ticker symbol change. The new CUSIP is G5223X100."

The new symbol should be available at https://cloud.staging.iexapis.com/stable/stock/market/batch?symbols=KXIN&types=quote&token=

**Comment by mikezliu** [comment]
Ok, thanks for the follow up
